version: "3.2"
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017

  api:
    image: node:16.14
    container_name: api
    restart: always
    env_file:
     - .env
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"